### ISSUE TITLE
Configuration file instructions and yq errors related to DB config

### ISSUE THREAD

**Issue by armchairancap** [paritytech/dotlake-community#6]
On Ubntu Linux, `sh` doesn't seem to work at all, while `bash` does.

```sh
$ sh ./dotlakeIngest.sh 
./dotlakeIngest.sh: 4: [[: not found
./dotlakeIngest.sh: 10: [[: not found
Unsupported operating system. Please install yq manually.
...

$ bash ./dotlakeIngest.sh 
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
          [jq_filter] [files ...]
yq: error: argument files: can't open '.relay_chain': [Errno 2] No such file or directory: '.relay_chain'
usage: yq [-h] [--yaml-output] [--yaml-roundtrip]
          [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH]
          [--indentless-lists] [--in-place] [--version]
```

With Bash, there seem to be issues with the statements such as `yq eval '.databases[0].type' config.yaml`

```sh
$ yq eval '.databases[0].type' config.yaml
usage: yq [-h] [--yaml-output] [--yaml-roundtrip] [--yaml-output-grammar-version {1.1,1.2}] [--width WIDTH] [--indentless-lists] [--in-place] [--version] [jq_filter] [files ...]
yq: error: argument files: can't open '.databases[0].type': [Errno 2] No such file or directory: '.databases[0].type'
```

In fact, `config.yaml` has the databases section marked out, so why is it being parsed in the first place?
I removed `#` in my `config.yaml`, but I also tried with `#` and neither way works. 

My DB section w/o the sharp:
```yaml
retain_db: true  # Set to true to retain database after the end of process.
databases:
  - type: postgres
    host: 127.0.0.1
    port: 5432
    name: dotlake
    user: postgres
    password: postgres
```

Can you take a look at the instructions and make it clear how it should be or maybe fix the installer script if the problem is there?
