### ISSUE TITLE
Any chance to skip relay chain to allow chains without it

### ISSUE THREAD

**Issue by armchairancap** [paritytech/dotlake-community#7]
I know this is outside of the scope right now, but is there a way to omit relay chain for networks that don't have it?

```yaml
relay_chain: 
chain: "xxnetwork"
wss: ws://192.168.1.70:63007
create_db: true  # Set to true if database needs to be created
retain_db: true  # Set to true to retain database after the end of process.
...
```

It appears that without it one could hack the startup script, but what happens after that is probably not good (haven't gotten that far, but I assume). If it could be skipped in config file and later (`if relay_chain == None`, etc) , that would let us proceed even at the cost of some functionality being unavailable and I could live with that. 

Another question/problem (maybe not highly relevant now, but..): what is the `chain` value supposed to be? Is that arbitrary or based on the SS58 [registry entry](https://github.com/paritytech/ss58-registry/blob/57344a5258f1abff8fdb4689e91ff594ca54f02d/ss58-registry.json#L509) entries? For some network this doesn't matter, but our network name has a space in it, but in SS58 registry it does not.

My network RPC and ID (+ metadata):

- [https://www.dwellir.com/networks/xx-network](https://www.dwellir.com/networks/xx-network)
- `ss58_format=55` (Metadata file: [xxnetwork.json (V14)](https://github.com/xxfoundation/xxchain/blob/617b35d134cf0fa568d37576204c0ca126e461e6/cli/res/xxnetwork.json))
